// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNXaDKyYgtAjIrIBx6CxKZ4ZsqU4fG7nY',
    appId: '1:340192368392:web:a0c51c51a01f07db427ebd',
    messagingSenderId: '340192368392',
    projectId: 'mycv-3bce2',
    authDomain: 'mycv-3bce2.firebaseapp.com',
    storageBucket: 'mycv-3bce2.appspot.com',
    measurementId: 'G-C9NYVRDN2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGC6809nUP7OU0YqWH8J259PEKs8-UouU',
    appId: '1:340192368392:android:592fe6f9685383f5427ebd',
    messagingSenderId: '340192368392',
    projectId: 'mycv-3bce2',
    storageBucket: 'mycv-3bce2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaDWcym9vH9k3GFVLno51wOMTPgm3lCSM',
    appId: '1:340192368392:ios:009404bed81383d2427ebd',
    messagingSenderId: '340192368392',
    projectId: 'mycv-3bce2',
    storageBucket: 'mycv-3bce2.appspot.com',
    iosBundleId: 'com.example.myResume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaDWcym9vH9k3GFVLno51wOMTPgm3lCSM',
    appId: '1:340192368392:ios:37042869db5af9e4427ebd',
    messagingSenderId: '340192368392',
    projectId: 'mycv-3bce2',
    storageBucket: 'mycv-3bce2.appspot.com',
    iosBundleId: 'com.example.myResume.RunnerTests',
  );
}
